language: rust
dist: xenial
rust:
  - stable
  # - beta
  - nightly
cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_script:
  - echo "$TRAVIS_RUST_VERSION" > rust-toolchain
  - rustup show
script:
  - cargo build --features bundled
  - cargo test --features bundled
notifications:
  email: false
